### ISSUE TITLE
[NumberGuesser] Equals

### ISSUE THREAD

**Issue by pavel-b-novikov** [DevilDimon/nsudotnet#4]
```"q".Equals(input))```

Поясните почему вы так странно сравниваете строки

**Comment by DevilDimon** [comment]
Это из Java, исправил

**Comment by pavel-b-novikov** [comment]
```if ("q" == input)```

Почему вы пишете так странно? Я знаю, что Каменский научил, но меня интересует объяснение по сути

**Comment by DevilDimon** [comment]
Если вы про порядок операндов, то ничем не обосновано, просто решил так написать
