### ISSUE TITLE
[NumberGuesser] 60 минут

### ISSUE THREAD

**Issue by pavel-b-novikov** [DevilDimon/nsudotnet#5]
``` Console.WriteLine("Time elapsed: {0} minute(s)", timeSpan.Minutes);```

А если я хочу играть больше 60 минут?

**Comment by DevilDimon** [comment]
Исправил, само закрылось из-за сообщения коммита, я открыл назад

**Comment by pavel-b-novikov** [comment]
А как все-таки вывести количество полных минут, которые человек играл? Ну т.е. все то же, что вы сейчас выводите, только в минутах

**Comment by DevilDimon** [comment]
Теперь вывожу полные минуты
